apiVersion: v1
data:
  password: cGFzc3dvcmQxMjM=  # demonstrative password
  username: YWRtaW51c2Vy  # demonstrative username
kind: Secret
metadata:
  creationTimestamp: null
  namespace: auth
  name: mongodb-secrets